spring:
  messages:
    basename: messages/messages
    encoding: ISO-8859-1
  main:
    banner-mode: 'off'
  jpa:
    open-in-view: true
    database-platform: org.hibernate.dialect.DerbyTenSevenDialect
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: /db/changelog/db.changelog-master.xml