package org.xmc.common.stubs.analysis;

public enum AnalysisType {
	ABSOLUTE_ASSET_VALUE,
	AGGREGATED_ASSET_VALUE,
	ABSOLUTE_AND_AGGREGATED_ASSET_VALUE,
	
	TRANSACTIONS,
	MOST_RECENT_TRANSACTIONS,
	
	INCOME,
	OUTGOING
}
